### ISSUE TITLE
Mpich: Slurm jobs fail for hostnames that do NOT end with a number

### ISSUE THREAD

**Issue by mrmhodak** [openhpc/ohpc#1016]
MPICH issue seen on OpenHPC 1.3.8. Adding also here so that a fix can be integrated

pmodels/mpich#3946

**Comment by mrmhodak** [comment]
Created pull requests #1020 and #1021 to fix this. The first one adds the patch into Sources, the second modifies spec file to use it.

This fixes the issue on my end.

**Comment by koomie** [comment]
@mrmhodak, builds in OBS are available with the patches applied to mpich v3.3.1. Since you seem to have some local hostnames that exposed this, can you possibly confirm the updated builds resolve the launch issue?

centos repo: http://build.openhpc.community/OpenHPC:/1.3:/Update8:/U1/CentOS_7/
sles repo: http://build.openhpc.community/OpenHPC:/1.3:/Update8:/U1/SLE_12/

**Comment by mrmhodak** [comment]
OK, so it is not fully fixed. The fix works for some cases, but still fails when when nodename contains underline as is the case in one of my servers. But it is an improvement.

**Comment by mrmhodak** [comment]
Actually, underscore is an illegal character in hostname, so the patch works well and the issue is fixed.

**Comment by koomie** [comment]
Excellent - thanks for checking. Local CI tests are looking fine also.
