### ISSUE TITLE
EasyBuild 4.0.0

### ISSUE THREAD

**Issue by boegel** [openhpc/ohpc#1033]
EasyBuild v4.0.0 has just been released.

The flagship feature is added support for running EasyBuild on top of Python 3.5+ (while Python 2.6 and 2.7 are still supported).

As indicated by the major version bump, it includes a couple of backwards-incompatible changes (a somewhat concise overview of the major changes is available at https://easybuild.readthedocs.io/en/latest/EasyBuild4-overview-of-changes.html).
`vsc-base` and `vsc-install` are no longer required, nor is `setuptools`.

I remember discussing with @koomie that it may make sense to only include this with OpenHPC v2.0 because the backwards-incompatible changes.

Any updates on that? Where should I send the PR to update the EasyBuild component to v4.0.0?

**Comment by amblakem** [comment]
Congrats on the 4.0.0 release!

> Any updates on that? Where should I send the PR to update the EasyBuild component to v4.0.0?

I believe the `2.0` branch is the proper target for this.  The branch naming was adjusted because the additional strings embedded in the branch names weren't used[1], but I believe this is the proper target for compatability breaking changes such as this.  Additionally, I think that the `2.0` branch's target distributions are CentOS 8 and OpenSUSE LEAP 15.1 so if you need to make spec updates for those platforms I believe that will be welcomed as well.

[1] Mentioned here: https://github.com/openhpc/ohpc/wiki/files/OpenHPC-TSC-Board-20190703.pdf

**Comment by boegel** [comment]
@amblakem Thanks a lot for the info!

I'll run some tests with EasyBuild 4.0 on CentOS 8 first to make sure things are working as expected before updating the `.spec` and target the `2.0` branch.

Is there any ETA for the OpenHPC 2.0 release?

**Comment by amblakem** [comment]
> Is there any ETA for the OpenHPC 2.0 release?

I believe the target is still to release OpenHPC 2.0 at supercomputing this year, so mid November.

**Comment by boegel** [comment]
@koomie @adrianreber Are there any other examples of Python tools that are packaged for OpenHPC?
Since EasyBuild v4.0.0 it's more straightforward to install EasyBuild like any other Python package (`pip install`), so there no more need for using the bootstrap script...

**Comment by adrianreber** [comment]
@boegel Looking at other Fedora/EPEL packages it uses the RPM macros `%py_build` and `%py_install`, so that would probably also be the right way for EasyBuild. Another idea would be to make EasyBuild part of EPEL/LEAP and OpenHPC can then just use the package from there. I can help you get EasyBuild into EPEL.

**Comment by boegel** [comment]
Packaging EasyBuild for EPEL makes a lot of sense...

I will need some help with that I think, I'm not foreign to RPM spec files, but I wouldn't call myself an expert either.

**Comment by adrianreber** [comment]
@boegel Can you provide an update PR to easybuild to have it included in out current 2.0 work?

**Comment by boegel** [comment]
@adrianreber I took a quick stab at it in #1136, but needs proper testing and probably a bit of extra work...

**Comment by boegel** [comment]
@adrianreber OK to close in #1136 (+ #1138) are merged?

**Comment by adrianreber** [comment]
Sure, close it.
