### ISSUE TITLE
python3-mpi4py-intel-impi-ohpc does not get mpicc path correctly

### ISSUE THREAD

**Issue by mppolak** [openhpc/ohpc#1261]
Pertains to series 2.x:
yum installing `python3-mpi4py-intel-impi-ohpc` gets the `/opt/ohpc/pub/libs/intel/impi/mpi4py/3.0.3/lib64/python3.6/site-packages/mpi4py/mpi.cfg` file wrong, with paths to mpicc, mpiifort etc. predefined as `/opt/intel/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin_ohpc` instead of using the one where it is actually installed. Of course I load modules properly befeore installation and `$PATH `is correct.
Similar issue for the version for OpenMPI (wrong OpenMPI version - I guess predefined somwehere as well), MVAPICH2 seems OK, but may also be predefined and may need updating.

**Comment by koomie** [comment]
This is going to resolve to the path to the relevant mpicc/mpicxx that were used when the package was built.  It's conceivable you have a different intel compiler version installed compared to what we used during the build and there is not much we can do about that.

Is this breaking something with your local use of mpi4py?

**Comment by mppolak** [comment]
We've had python codes that internally compare the available `mpicc` etc. with the output of `mpi4py.get_config()`, and raise an error if they don't match. Commenting that out fixes the problem and everything works fine of course, but I figured there maybe other cases like this.
I guess they were coded this way to prevent having a case where `openmpi` is loaded while `mpi4py` was compiled with `impi` or the other way around. The way modules are generated when installing ohpc repos prevents this from happening so it is not an issue in general but will still raise the error. Just thought its useful to be aware of that. If theres not much to be done about it i'll just get rid of that piece of the code.
Thanks for the quick response.

**Comment by koomie** [comment]
That's certainly a good thing to check for consistency, but I think it may be a bit too restrictive since most everything is dynamic libs and you don't have to have the exact same versions between build/execution (and it is certainly problematic in the case of using intel psxe since we can't control what version a site might have installed locally).  I guess what you are really trying to prevent against is having an inconsistency with the compiler or MPI family that mpi4py was built with compared to what is in the user's current environment.

Perhaps you can consider asking the authors to issue a warning instead?  Or, in the case of ohpc-provided builds you could parse the strings from `mpi4py.get_config()` to determine their compiler/mpi family combination and make sure that combination is consistent with the execution environment.
