### ISSUE TITLE
llvm10 build dependency problem

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#1318]
The current llvm10 build in 2.1 factory is un-installable so pulling from the release. At lease one of the issues is that `libunwind` is called out as an explicit conflict (and libunwind-devel is pulled in by `scorep`).  This looks to be incorrect since the ohpc build will avoid conflicting with the distro provided version via our rpm plugin hook that appends a delimiter to the .so dependency.

```
# rpm -qp llvm10-compilers-ohpc-10.0.1-1.9.ohpc.2.1.x86_64.rpm --provides | grep unwind
libunwind.so.1()(64bit)(ohpc)
```

To include for next release, will need to get this resolved and tested. 

- An optional installation needs to be called out in the docs
- Update test-suite to include basic testing

**Comment by jcsiadal** [comment]
Finally looking at this. Having another libunwind installed definitely caused build failures, but don't remember if it was a runtime issue. It may have just been a mistake on my part not using BuildConflicts instead of Conflicts.

I'm running some builds right now with 12.0.1. Back with llvm9, I wanted to copy LLVM's included tests over to ohcp-test, but they required the static libs to be installed. I had to use an intermediary process of building with static and tests, running the tests, rebuilding without, doing a few manual compile tests, and then submitting.  I'll see if I can run llvm12 tests with just shared libs.
