### ISSUE TITLE
vsc-base (v2.4.16)

### ISSUE THREAD

**Issue by JohnWestlund** [openhpc/ohpc#132]
This is a source for EasyBuild -- update?
https://pypi.python.org/pypi/vsc-base/2.4.16

**Comment by boegel** [comment]
As EasyBuild maintainer: there's no pressing need to update to the latest vsc-base version for EasyBuild v2.4.0 (or even v2.5.0), but at some point there will be

Most of the changes in the latest versions of vsc-base are due to splitting off vsc-install as a stand-alone package, and changes to the tests for vsc-base.

That being said, I'm willing to help out with this if needed, since it may not be trivial due to vsc-install being required now.

**Comment by koomie** [comment]
Not updating this dependency based on @boegels recommendation.  Closing this out.
