### ISSUE TITLE
Lustre 2.12.8 client supporting EL/Rocky 8.5 kernel 

### ISSUE THREAD

**Issue by usawangwit** [openhpc/ohpc#1399]
Now that the Lustre 2.12.8 is release https://wiki.lustre.org/Lustre_2.12.8_Changelog 
The RHEL 8.5 client is supported. 
Should we expect an update for the package lustre-client-ohpc for OpenHPC 2.4 
or 
will this arrive later for the 2.5 release?

**Comment by aflyhorse** [comment]
upvote for an update 🔢

**Comment by liv-acollins** [comment]
Since 2.4 was the EL 8.5 release it would be great if this had been included once it was released for the sake of compatibility.

Is there any possibility of this still making an appearance in 2.4 or will it now be pushed to 2.5?

As previously with 2.12.7, I'm happy to test an early release on Rocky.

**Comment by adrianreber** [comment]
Closing as it seems to have been fixed by #1399
