### ISSUE TITLE
ohpc-intel-geopm breaks dnf update

### ISSUE THREAD

**Issue by nsonoda** [openhpc/ohpc#1643]
Hi!

I'm getting errors with ohpc-intel-geopm when I try to dnf update. I removed the geopm-intel* packages and did dnf update, and I was able to update my packages. But I reinstalled ohpc-intel-geopm, and then dnf update got errors again: https://pastebin.com/fnTfTjJe

Thank you!

**Comment by adrianreber** [comment]
Thanks for the report. That is our error.

With each new release our buildsystem starts at the release value 1.1.

Because we had to rebuild all packages for the new Intel compiler the 2.6 branch has the same package geopm in the version 1.1.0. The release in the 2.0 branch 7.1.ohpc.2.0 and in the 2.6 branch 3.2.ohpc.2.6:
```shell
$ rpmdev-vercmp 1.1.0-3.2.ohpc.2.6 1.1.0-7.1.ohpc.2.0
1.1.0-3.2.ohpc.2.6 < 1.1.0-7.1.ohpc.2.0
```
RPM decides, based on the version and release number, that the old package is newer. This will be fixed with the next release (2.7 probably).

For now, you have to exclude geopm from your updates.

@koomie FYI
