### ISSUE TITLE
ipmitool issue

### ISSUE THREAD

**Issue by drscottsimpson** [openhpc/ohpc#1865]
When trying to use the following command
`ipmitool -E -I lanplus -H ${bmc_ipaddr} -U root chassis bootdev pxe options=persistent
`
I get the following error:
`Unable to read password from environment
Password:
Address lookup for -U failed
Could not open socket!`

**Comment by adrianreber** [comment]
Thanks for your report. I see three errors here:

```
Unable to read password from environment
```

This is because you use `-E`. This parameter expects the password to be in a environment variable. The man page says:

```
-E     The remote server password is specified by the environment variable IPMI_PASSWORD or IPMITOOL_PASSWORD. The IPMITOOL_PASSWORD takes precedence.
```

please set the password via the corresponding environment variable or use the `-P` parameter.

```
Password:
```

This is `impitool`'s prompt for you the enter the password because the password is not provided via an environment variable or via `-P`.

```
Address lookup for -U failed
Could not open socket!
```

This is because the host variable is empty `${bmc_ipaddr}`. Now `ipmitool` tries to use `-U` as the host name.

From my point of view it seems you are using the command without setting the necessary environment variables. Without context what you are trying to do it is not possible to understand what you are really asking for.
