### ISSUE TITLE
openHPC 3.0 + opensuse leap 15.5

### ISSUE THREAD

**Issue by dvdsnchzIT** [openhpc/ohpc#1883]
Hi,

I'm building a new cluster in my lab and I found some errors in the documentation based on this file <https://github.com/openhpc/ohpc/releases/download/v3.0.GA/Install_guide-Leap_15-Warewulf-SLURM-3.0-x86_64.pdf>.

## 3.8.4.5 Add BeeGFS

The ```perl -pi -e "s/^allow_unsupported_modules 0/allow_unsupported_modules 1/" \
$CHROOT/etc/modprobe.d/10-unsupported-modules.conf``` can't work for master and nodes because ```/etc/modprobe.d/10-unsupported-modules.conf``` doesn't exist.

It is available in ```/lib/modprobe.d/10-unsupported-modules.conf```

## 3.9.1 Assemble bootstrap image

When I try to ``` wwbootstrap `uname -r` ``` I got this error
```ERROR:  Could not locate the configured cacert file```

In  ```/etc/warewulf/provision.conf``` ```cacert = /etc/pki/tls/certs/ca-bundle.crt``` which does not exist

But it works with ```/etc/ssl/ca-bundle.pem```

**Comment by adrianreber** [comment]
Thanks for the report. Unfortunately we didn't test the beegfs part at all for the 3.0 release. We should have removed it from the documentation.

The second error is interesting because I see it works in CI and also the source code points to the right path: https://github.com/openhpc/ohpc/blob/ee436b589fbf544891ad083b2277b3707e86d8b6/docs/recipes/install/common/warewulf_setup_sles.tex#L16

Have you used the right recipe/documentation?

**Comment by dvdsnchzIT** [comment]
No problem for BeeGFS, sad if removed :-( 

For the wwbootstrap, it's possible I was using an old revision or version :sweat_smile:

**Comment by adrianreber** [comment]
> No problem for BeeGFS, sad if removed :-(

It might come back (especially with community help). We just didn't have time to test it.

> For the wwbootstrap, it's possible I was using an old revision or version 😅

If you are sure it works for you, please close the ticket or we can continue to look if we find an error.

**Comment by dvdsnchzIT** [comment]
It can be closed !
