### ISSUE TITLE
Separate MKL module from Intel

### ISSUE THREAD

**Issue by t-brown** [openhpc/ohpc#221]
Should there be a separate MKL module when loading the Intel suite? At the moment there isn't and `$MKLROOT` gets set when loading `intel`.

This leads to an inactive module when swapping from `gnu` to `intel`:

```
$ ml gnu
$ ml mkl
$ ml -gnu intel

Inactive Modules:
  1) mkl

$
```

It is also inconsistent when explaining dependencies to users.

**Comment by koomie** [comment]
Right - the thought here originally was that MKLROOT was probably what people wanted and it was set directly in the `intel` module.  I agree thought that the asymmetry may be a potential source of confusion. Note that we're in the process of removing MKL and other intel compiler stuff, so this will change in the short term since it will not be present. However, I propose we leave this open and revisit once we have a mechanism for reintroducing builds that leverage things like MKL and the intel compilers.

**Comment by mabraham** [comment]
It's rather awkward to try to use MKL without the Intel compilers, so I'd suggest MKL be bundled with the intel module, or depend on it.

**Comment by sjpb** [comment]
Being able to install MKL without `icc` does have some use - e.g. it provides a precompiled HPL.
