### ISSUE TITLE
Scalasca (2.3.1)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#318]
http://www.scalasca.org/software/scalasca-2.x/download.html

**Comment by koomie** [comment]
@surak, one question that came was whether the build needed to consider optional dependencies (like SIONlib), or if standard usage can proceed without?

Thanks.

**Comment by surak** [comment]
A standard version is enough. How long is the release cycle? Currently I am considering to submit Cube4.4 (which MIGHT come out for SC) but right now I only have 4.3 technology preview. What you suggest me to do?

**Comment by koomie** [comment]
We are also endeavoring for a release right before SC, so we are aiming to do this quickly. Consequently, we'll need to go with the released versions that are available now. If, however, you had updated releases next week, we could likely go with those too.

**Comment by surak** [comment]
@koomie Hi Karl, I met with the SIONLib's and with Score-P's developers, and they actually would like to have SIONLib as a standard feature of OTF2 (which is a mandatory dependency of Score-P).

One thing is that the version of SIONLib that ScoreP uses is not standard - in order to avoid problem when instrumenting codes that uses SIONLib themselves (It would be the same with an application that uses mpi being instrumented by an mpi program before the existence of PMPI). 

So I would ask you here to use this special version of SIONLib on the build of otf2/scorep, and I will make a standard submission request for the standalone SIONLib. Is that ok for you?

PS: I will publish the new release of the two SIONLib versions for Monday.

**Comment by surak** [comment]
Hi,
as I mentioned, there is a "tools version" of sionlib at http://apps.fz-juelich.de/jsc/sionlib/download.php?version=1.7.0l  (mind the "l" at the end).

**Comment by crbaird** [comment]
tests passing in CI
