### ISSUE TITLE
Broken python dependencies

### ISSUE THREAD

**Issue by chuckatkins** [openhpc/ohpc#322]
Many of the python packages are depending on the existence of /bin/python.  On EL7, /bin is a symlink to /usr/bin, so the actual file exists in /usr/bin/python.  In a recent update in the system python-2.7.5-38.el7_2.x86_64 -> python-2.7.5-39.el7_2.x86_64, the "provides" was changes to no longer specify /bin/python, only /usr/bin/python.  Several of the OHPC python packages (easybuild, numpy, scipy, petsc, to name a few),  list a dependency on /bin/python instead of /usr/bin/python.  So even though (/bin -> /usr/bin)/python exists, yum doesn't see it as it only sees the removal of /bin/python and fails to update python because of broken dependencies in the ohpc packages.

A workaround is to uninstall the conflicting ohpc packages, update python, and reinstall them since the install will first look for the file in the rpm database and when not found then try to resolve it on the filesystem, which it can do successfully.

**Comment by koomie** [comment]
Thanks for the report. We'll take a further look.

**Comment by koomie** [comment]
This issue was ultimately the same gotcha as reported in #451 which is related to the use of `su -` by the underlying obs build system to spawn rpm builds.  On Centos, this was inadvertently placing `/bin` in front of `/usr/bin` in `$PATH` for the build environment.  We have devised a small patch for the obs build environment to fix the path for newer rhel variants.  The updated builds for Easybuild, numpy, scipy, petsc should all now have dependencies detected for `/usr/bin/python` instead of `/bin/python`. 

These will be available with the next 1.3.2 release.
