### ISSUE TITLE
BeeGFS client

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#340]
https://git.beegfs.com/groups/pub

**Comment by crbaird** [comment]
Hi @breuner. Does the BeeGFS project publish source tarballs?

**Comment by breuner** [comment]
@crbaird only "indirectly" through tags in our gitlab repository. You can see an overview for the current major release series (BeeGFS v6.x) here: https://git.beegfs.com/pub/v6/tags (current latest stable is 6.4)  
Was that what you meant?

**Comment by koomie** [comment]
Sort of, but not exactly. We need a canonical URL that can be used to obtain a src tarball as input for the build process. There are a number of projects that we pull from GitHub and the release mechanism there allows for such tar balls. I'm not sure what git backend you are using...maybe it has a similar feature?  Alternatively, if you posted tar balls associated with a given release tag somewhere publicly, we could use that location.

**Comment by crbaird** [comment]
Also, we'd ideally like to have a tarball for each component as opposed to the monolithic source tree.

**Comment by breuner** [comment]
Regarding src tarball: This URL should be suitable: https://git.beegfs.com/pub/v6/repository/archive.tar.gz
It will get you the latest stable stable version of the current major release series (v6.x). (Just for clarification: We push only stable versions to this particular repository, that's why pulling the master tarball is the right thing here.)  
  
Regarding multiple tarballs: The components are sharing bits of the build system, that's why we have them together in one tarball. For the client, the relevant packages are beegfs-{client,helperd,utils,common}. Would it help if we add an option to the beegfs_auto_package/make-rpms.sh script to build exactly these packages instead of building all packages?

**Comment by crbaird** [comment]
@breuner In lieu of rebuilding the BeeGFS packages, we opted to document enabling the public BeeGFS repos and added instruction for installing and configuring the clients to connect to an existing server to the OpenHPC install guide. Some basic tests were added to the OpenHPC test suite, and they are passing in our CI for both CentOS and SLES.

**Comment by koomie** [comment]
Tests passing in CI, closing this out.
