### ISSUE TITLE
FFTW: single, double and long double versions

### ISSUE THREAD

**Issue by a74nh** [openhpc/ohpc#463]
Currently FFTW is only built for one precision type.

Could we please add the config options to also build double and long double versions?
This would produce 3 versions of the library.

This should just be a small change in the configuration options at build time.

Use case here was someone trying to build the namd using openhpc.

**Comment by a74nh** [comment]
Configure options (not enabled by default):
 --enable-single         compile fftw in single precision
  --enable-float          synonym for --enable-single
  --enable-long-double    compile fftw in long-double precision
  --enable-quad-precision compile fftw in quadruple precision if available

**Comment by boegel** [comment]
It's actually a little bit more complex than that, since you can only enable one particular precision per build, so you need to run the `./configure`, `make`, `make install` cycle multiple times, once for each precision you want to install.

There's also other caveats, like `--enable-avx` is only compatible with `--enable-single` the default (double) precision (note, there's no --enable-double`), not with higher precisions, and quad precision is not supported on ARM, etc.

See the logic in https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/f/fftw.py

**Comment by a74nh** [comment]
This would explain why centos has multiple rpms:

yum search fftw-libs
  fftw-libs.aarch64 : FFTW run-time library
  fftw-libs-double.aarch64 : FFTW library, double precision
  fftw-libs-long.aarch64 : FFTW library, long double precision
  fftw-libs-single.aarch64 : FFTW library, single precision

I think it would make sense for ohpc to split out into multiple .rpms too.

Agree it's going to make the .spec file a little messy, but I think this should be all contained within a single .spec file (rather than creating multiple packages).

That would also mean the one .spec file produces a slightly different list of .rpms on x86 and aarch64. (eg no quad rpm on aarch64), not sure if that it going to be a problem.

**Comment by adrianreber** [comment]
Closing this as we are building with multiple precisions for some time now: https://github.com/openhpc/ohpc/blob/3.x/components/parallel-libs/fftw/SPECS/fftw.spec#L20
