### ISSUE TITLE
TAU and pdtoolkit are broken out of the box

### ISSUE THREAD

**Issue by jlinford** [openhpc/ohpc#686]
Let me know if you'd like some help configuring TAU.  The current configuration looks ... strange.

Problems:

- Both TAU and pdt are not relocatable.  Absolute paths are encoded throughout their binaries and scripts, and these paths are set at build time.  For example, if TAU (or PDT) is configured with the -prefix option, e.g `-prefix=/tmp/opt/ohpc/pub/libs/gnu7/openmpi3/tau/2.26.1` then the whole package *must* remain at `/tmp/opt/ohpc/pub/libs/gnu7/openmpi3/tau/2.26.1` or it will break.

- Only one TAU makefile is available!  This is related to existing issue #683 .  TAU requires binary compatibility with the application so it must be reconfigured for every possible unique combination of MPI/OpenMP/compiler/support-libs/etc. that the user may need.

- TAU is being configured with deprecated flags: `-CPUTIME -PROFILE -PROFILECALLPATH -PROFILEPARAM`.

I strongly recommend replacing TAU and PDT native installations with TAU Commander from ParaTools, Inc.  www.taucommander.com.  That tool will automatically reconfigure TAU and PDT as needed so you don't have to guess what options your users will need.

**Comment by jlinford** [comment]
Followup: I've installed TAU Commander on Arm's ThunderTX2 cluster in Austin, TX.  Seems to be working OK.

**Comment by crbaird** [comment]
Hi @jlinford. Thanks for taking a look at this. I don't doubt that the OHPC TAU packages have room for improvement and we we welcome the help, but I disagree with your characterization that they are broken out of the box. In order to package as an RPM, relocation is necessary. Most of the strangeness in the spec file is due to this requirement. The issue of binary compatibility is addressed by providing builds of TAU for every permutation of compiler and MPI runtime that OpenHPC supports. In fact, a single makefile was working fine until 2.27, when an OpenMP code stopped  profiling with a TAU lib including MPI. As you well know TAU is an expansive code with many useage modes, and it could well be that we don't support all of them. We aim to provide tested binary packages that do at least something useful, and hopefully that usefulness increases over time. Regarding the deprecated config options: fair enough. This spec file has been carried since 2.24, and has no doubt accumulated cruft.

**Comment by jlinford** [comment]
Thanks @crbaird !  Can you please explain what you mean by "In order to package as an RPM, relocation is necessary. Most of the strangeness in the spec file is due to this requirement"?  I fully agree that software must be relocatable to be packaged as an RPM.  TAU and PDT most certainly are not relocatable, and cannot be made relocatable.  I came across this issue on our cluster because TAU and PDT were building under `/tmp` but being installed under `/opt`, hence "broken out of the box."  

Do the TAU/PDT RPMs distribute source and compile in `%post`?  Or must OpenHPC be installed in the same filesystem location on all systems?  Or are you doing some other magic to make sure the absolute paths that get baked into TAU/PDT binaries and scripts are correct?

**Comment by phpHavok** [comment]
Also, one of our users just reported another more minor issue. Lines 182 and 189 of `/opt/ohpc/pub/libs/intel/openmpi3/tau/2.28/bin/paraprof` use `$MACHINE` without quotes (i.e., not `"$MACHINE"`) resulting in bash parser errors when `$MACHINE` is the empty string.

**Comment by koomie** [comment]
Thanks for the report on`$MACHINE` in the paraprof script. We created a quick patch to fix those lines which will be included in tau builds for the v1.3.9 release.
