### ISSUE TITLE
singularity.spec includes own license header

### ISSUE THREAD

**Issue by adrianreber** [openhpc/ohpc#851]
Just as the recent discussion about the license header in the pbspro.spec I just saw the same in the singularity.spec. It claims to be  3-clause BSD license. Just as with all other SPEC files in OpenHPC I think this should be removed as we distribute the SPEC files under the Apache 2.0 license.

I can submit a pull request.

**Comment by jmstover** [comment]
Leave the copyright header and IMO your fine. ;)

Also don't change the `License:`  entry, as that's the license of the Singularity software, not the file.

**Comment by adrianreber** [comment]
Yes, but the OpenHPC project says, that all SPEC files are licensed under Apache 2.0. I am not talking about the license of the software or the License tag. Only about the license of the SPEC file.

**Comment by jmstover** [comment]
Right ... and as long as you leave the copyright header you're clear. You can relicense from OHPC under Apache 2 all you want. But to keep with the original BSD license, the copyright header needs to stay intact. That's all I was saying.

**Comment by adrianreber** [comment]
And the singularity project is not willing to relicense the SPEC file like it happened in #757.

**Comment by jmstover** [comment]
@adrianreber ... I think relicensing is an impossibility because of the source (LBNL/Government funding). So that, as comes from upstream, needs to stay under BSD. But as I said, the BSD license doesn't preclude you from relicensing under Apache 2, as long as you keep the original copyright header.

@gmkurtzer ... Can you speak up on relicensing just the SPEC file under Apache 2 on the 2.x Singularity? Or is that an impossibility because of the Government source?
