### ISSUE TITLE
buildtest (v0.7.5)

### ISSUE THREAD

**Issue by koomie** [openhpc/ohpc#920]
http://buildtestdocs.readthedocs.io/en/latest/

**Comment by shahzebsiddiqui** [comment]
@koomie  please use https://buildtest.readthedocs.io/en/latest/  for documentation. Please let me know when you start working on this. I will try to keep documentation up to date.

**Comment by crbaird** [comment]
Hi @shahzebsiddiqui - The docs mention python > 3.6 as a requirement, and indeed we're seeing an error when building with the default CentOS python 3.4. I'm able to build locally with python 3.7.3, so I wonder what the chances are for working around with a slightly older python. You can see the build results here:
https://build.openhpc.community/package/live_build_log/home:crbaird/buildtest/CentOS_7/x86_64

**Comment by shahzebsiddiqui** [comment]
Hi @crbaird,
buildtest makes use of fstrings which was introduced in version 3.6 see https://docs.python.org/3/whatsnew/3.6.html. It was introduced in https://www.python.org/dev/peps/pep-0498 I believe the error you are getting is due to python version.

buildtest makes use of fstrings which is a faster implementation of string formatting. You can check https://realpython.com/python-f-strings/ for more details on different format strings in python.

**Comment by crbaird** [comment]
Hi @shahzebsiddiqui,
We're basing the OpenHPC v1.3.9 release on CentOS 7.7 and SLE 12.4, so we now have a good python3.6 with which to build. I've had good luck building the buildtest framework from a clone of your master branch, but less so using the 0.6.3 release tarball. Would it be possible to package up a new release of buildtest?

**Comment by shahzebsiddiqui** [comment]
oh yea, can you please not use version 0.6.3. Is it okay to use the master branch. You should be able to download via https://github.com/HPC-buildtest/buildtest-framework/archive/master.zip

As per the installation its only pip packages and requirements file is provided. See https://buildtest.readthedocs.io/en/latest/setup.html#installing-buildtest

I stopped creating release since project is in active development and not in stable release. The devel branch is about 40 commits ahead of master. I dont plan on merging devel to master after SC'19 (end of Nov) because I need to retain the old content. So you should be safe to use master. 

I honestly, dont know version 0.6.3 https://github.com/HPC-buildtest/buildtest-framework/commits/v0.6.3 which is at commit 288 (Oct 2018) and whether this is even stable . Master branch is at commit 550 and it should be ok.

**Comment by crbaird** [comment]
Is there any way you could tag the current master? A release is ideal for us since we get a more or less immutable tarball to build from for posterity.

**Comment by koomie** [comment]
We also need the tag to have a reasonable version string so that future RPM upgrades can be accommodated.

**Comment by shahzebsiddiqui** [comment]
Sure I can make a tag for openhpc release. Please tell me the release
number and i will name the tag accordingly.

I'll tag against Master branch

**Comment by koomie** [comment]
It really should come from you and be something that will be incremented at the next formal release. Everything on the github release page is listed as Pre-release, but your last tag was `v0.6.3`. So, perhaps tagging as `v0.6.4` makes sense and then increment on top of that for next stable release.

**Comment by shahzebsiddiqui** [comment]
I have pushed a new tag ``v0.7.0`` see https://github.com/HPC-buildtest/buildtest-framework/tree/v0.7.0. Hope this is okay. It should match the ``HEAD`` of master and documentation for master branch https://buildtest.readthedocs.io/en/latest/ should be compatible with this release. The latest devel branch is in active development and its documentation https://buildtest.readthedocs.io/en/devel/ is quite different. Hope this will work.

Once the package is built from OpenHPC end, i can follow up with a release on a more frequent basis, i use to be doing this in past, but had stopped for some time.

**Comment by shahzebsiddiqui** [comment]
@koomie do you guys need anything from my end to get buildtest in openhpc. Btw, i have now starting releasing new versions with tag so you are welcome to use the latest tag of stick to version ``0.7.0`` if you desire.

**Comment by shahzebsiddiqui** [comment]
Hey @koomie this version is quite old is there chance this will get into openhpc if so the latest version is v0.9.3

**Comment by shahzebsiddiqui** [comment]
@koomie just forgot about this issue i posted a while back any chance we can get buildtest as part of OpenHPC. This version is quite outdated we could try the most recent version 0.13.0.
