### ISSUE TITLE
Intel MPI  cannot be installed without intel compiler

### ISSUE THREAD

**Issue by omula** [openhpc/ohpc#955]
/opt/ohpc/admin/compat/modulegen/mod_generator.sh is provided by intel-compilers-devel-ohpc-2019-6.1.ohpc.1.3.7.x86_64

If icc is not installed the installation of this package will not succeed and mod_generator.sh will not be available.

intel-compilers-devel-ohpc.x86_64 will not install as mod_generator.sh won't be available.

Should mod_generator.sh be provided by another package?

**Comment by koomie** [comment]
Am I understanding correctly that you would like to install the openhpc compatibility package for Intel MPI (`intel-mpi-devel`), but don't have the Intel compilers also installed?

**Comment by omula** [comment]
Exactly as Intel MPI can now be downloaded with community support.

**Comment by koomie** [comment]
Ok, that's a new use case - it should be doable. Will look into it further.

**Comment by ChrisDowning** [comment]
Essentially everything from the Intel performance libraries (MPI, MKL, DAAL etc) except ICC can be installed with community support - package install details [here](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-yum-repo) and license details [here](https://software.intel.com/en-us/articles/end-user-license-agreement).

**Comment by DarrenPR** [comment]
Just to add on to this issue, as my issue seems related enough to not create a new issue, it appears that the OpenHPC compatibility RPMs cannot install without the Intel packages being present in the RPM database where the compatibility installs occur.

I have a system that uses Slurm/Warewulf and has Intel Parallel Studio available to it. Currently, Parallel Studio currently gets installed into the Warewulf chroot directly and is available for the OpenHPC compatibility RPMs. However, the install takes some time and uses a large amount of space for each version of Parallel Studio in each of the chroots that are used. I would like to have the Parallel Studio version(s) installed just once on a shared location and made available to the chroots as they are installed. Since the current method the compatibility RPMs use for PSXE installs uses rpm -qal, even when the files are present to the chroot, the compatibility RPMs fail because the RPM database does not report the files having been installed via a package it can query.

I believe that whatever fix is implemented to resolve this issue should be implemented in a way that also handles the shared-location-install capabilities of Parallel Studio.

**Comment by koomie** [comment]
@DarrenPR, I have made a change to the impi compatibility package such that it does not require the compilers to also be installed. However, that is separate from the issue you describe, but I believe you can do something similar to what we do in our CI test environment to have a single, shared instance of the intel toolchain. In our case, we override the default install path of the PSXE packages to reside in a location that we are NFS exporting to cluster hosts. If you use the silent install option, you can do this by updating the following var:

```
# Install location, valid values are: {/opt/intel, filepat}
PSET_INSTALL_DIR=/opt/ohpc/pub/intel 
```

 Then, we install the compatibility package on the same host. Per our standard ohpc recipes, `/opt/ohpc/pub` is an NFS export so the resulting modulefile that is created is also shared with cluster hosts.

**Comment by koomie** [comment]
impi-devel has been updated to relax requirement to have underlying intel compilers installed.

**Comment by marseaplage** [comment]
Hi guys some of you have tried to install: lmod-default-intel-impi? in my case it says that it requires intel-impi-ohpc but I haven't found it yet !! I get the error of missing package
